import { createFileRoute, Link } from "@tanstack/react-router";
import { AmbientBackground } from "@/components/devdiary/AmbientBackground";
import { MobileDock } from "@/components/devdiary/MobileDock";
import { TopBar } from "@/components/devdiary/TopBar";
import { MoodOrb } from "@/components/devdiary/MoodOrb";
import { ArrowLeft } from "lucide-react";

export const Route = createFileRoute("/profile")({
  head: () => ({
    meta: [
      { title: "Your portrait — DEV DIARY" },
      { name: "description", content: "Settings, account, and your evolving portrait." },
    ],
  }),
  component: ProfilePage,
});

function ProfilePage() {
  return (
    <div className="relative min-h-screen pb-36">
      <AmbientBackground />
      <TopBar
        right={
          <Link to="/" className="text-sm text-muted-foreground hover:text-foreground flex items-center gap-1">
            <ArrowLeft className="size-4" /> Home
          </Link>
        }
      />
      <main className="mx-auto max-w-2xl px-5 sm:px-8 pt-10 space-y-10">
        <header className="flex items-center gap-5">
          <MoodOrb size={120} mood="A." caption="You" hue="violet" />
          <div>
            <p className="text-eyebrow text-foreground/55">Your portrait</p>
            <h1 className="text-display text-3xl text-white">Alex Moreno</h1>
            <p className="text-sm text-muted-foreground">142 reflections · 4 chapters · since Jan 2024</p>
          </div>
        </header>

        <section className="space-y-3">
          <p className="text-eyebrow text-foreground/55">This year, in three sentences</p>
          <div className="glass-card-strong rounded-3xl p-6 space-y-3">
            <p className="text-display text-xl text-white/90 leading-snug italic">
              "You moved cities, started something fragile, and learned to call your mother
              without a reason. You stopped explaining yourself to people who were never going
              to read past the first sentence. You are getting quieter on the outside and louder on the inside."
            </p>
            <p className="text-xs text-muted-foreground">Generated by your reflection engine · refreshed weekly</p>
          </div>
        </section>

        <section className="space-y-3">
          <p className="text-eyebrow text-foreground/55">Settings</p>
          <div className="glass-card rounded-3xl divide-y divide-white/5 overflow-hidden">
            <Row label="Account" value="alex@example.com" />
            <Row label="Daily prompt time" value="21:00" />
            <Row label="Sealed letters" value="3 in transit" />
            <Row label="Export archive" value="JSON · Markdown" />
            <Row label="Theme" value="Celestial dark" />
          </div>
        </section>

        <section className="text-center pt-4">
          <button className="text-sm text-muted-foreground hover:text-white transition-colors">
            Sign out
          </button>
        </section>
      </main>
      <MobileDock />
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between p-5">
      <span className="text-sm text-foreground/85">{label}</span>
      <span className="text-sm text-muted-foreground">{value}</span>
    </div>
  );
}
